### PR TITLE
i47 added udisks2 plugin

### PR DESCRIPTION
**Pull request by info-cppsp**
i47 fix
https://github.com/mate-desktop/mate-sensors-applet/issues/47

see changed readme here
https://github.com/info-cppsp/mate-sensors-applet

My 1. question would be if and where I could place my e-mail as a contributor - as this is a big change.
The 2.: the README should be updated to show the udisks plugins
like:
    * For hddtemp support:
          o hddtemp running in daemon mode
For HDD/SSD temp support:
udisks plugin (deprecated) and udisks2 plugin (new in 2017-09)

I can't find the right page, but AFAIK hdd temp can't read SSD temp. Now I have found some pages, that it can, with some hacking.
https://lists.nongnu.org/archive/html/hddtemp-dev/2016-03/msg00001.html

Good / no good / other?

3. From the above readme maybe some infos could be taken as a wiki, like what packages are needed to compile the project...

Also, I have added the autogenclean.sh. Run it with bash to get rid of the configure mess.

Consider this plugin a beta, please review and comment / help.

### CODE REVIEW

**Comment by monsta** [comment]
I think we can just port current udisks plugin to udisks2, given that original udisks is gone from most distros these days.

**Comment by monsta** [comment]
As for hddtemp, it can read SSD temps out of the box, but not for all SSD models. I've seen people had problems with Samsung EVO drives - hddtemp doesn't recognize their sensors or something.

My Crucial SSD is recognized:

```
$ sudo hddtemp /dev/sdb
/dev/sdb: Crucial_CT480M500SSD1: 35°C
```

**Comment by info-cppsp** [comment]
I happen to have an EVO...
Also, AFAIK hddtemp needs a daemon, which you would have to install...

**Comment by info-cppsp** [comment]
4. Please check whether or not the configure switch --disable-udisks2 is working.
For me it doesn't seem to 'make' the plugin, but after installing it is still there...
5. Please have a look at the memory consumption. A freshly compiled msa starts with 30 MB, then crawls up to 80 MB in 12 hours... It is possible that I have a memory leak in the update_device() function of my plugin, as that is run every 2 seconds...
Still, 30 MB is a lot, as the version on mint 17.3 - msa 1.12 (?) - is getting by with 7 MB.

**Comment by info-cppsp** [comment]
after 2 hours, with only an i2c-sys CPU temp sensor, mem stays at 32 MB

**Comment by info-cppsp** [comment]
after 2 hours, with 2 udisks2 sensors also enabled, mem is at 33,6

**Comment by info-cppsp** [comment]
ok, so I think, I have fixed the memory leak with the new commit. I have run it for 16 hours, and msa is still at 32 MB. (which is still a lot...)
The issue was that I was doing function chaining - like fn1(fn2(fn3(param))) - BUT the param and the function return values were in this case a pointer. And of course they have to be freed, which I didn't do.
I could go around this by using a separate function and function pointers like

GVariant * myfunc(void* funcptr, GVariant* param) {
  GVariant* retval = funcptr(param);
  g_variant_unref(param);
  return retval;
}

but I guess it is much more understandable to just do one function at a time and then free the pointer, so that's what I went with.

I also added some error handling code for the dbus functions, where there was none before.

**Comment by info-cppsp** [comment]
after a week, the mem consumption is at 27,2 MB.

**Comment by raveit65** [comment]
@monsta 
In fedora we have udisk and udisk2 and the there is no attempt to remove the old one.
So, i suggest not to remove the old one for the moment, it doesen't hurt to leave it there.
I tested the PR already, see report.
https://github.com/mate-desktop/mate-sensors-applet/issues/47#issuecomment-326401416
But my SSDs have only dummy sensors which displays always 30°C with udisks and udisks2.
So i think all is good.
Not sure why we need a autoclean.sh as there are no files to clean if you use our git repo.

**Comment by info-cppsp** [comment]
I can only state, that udisks is gone in mint 18.2. As it is deprecated, it is probably going to be removed from other distros as well.

About autogenclean.sh: AFAIK the gnu build process creates configure files and then with make compiles the code. make install install the program on your system. Now, If you want to remove all files created by the make command, you simply write 'make clean'. The same cannot be done for the configure. If you don't delete those files manually, they could be mistakenly committed to the repo.
It is a shortcut to be able to use 'commit -a' or make a patch, without having to worry about these configure files.
I'm sure there are better ways to achieve the same effect, so please feel free to share.

**Comment by raveit65** [comment]
Well, i use always 2 folders of an application.
Ie. mate-sensors-applet and mate-sensors-applet-compile.
One for making commits and the other one for compiling, in result i have always a clean folder ;-)
But Ok, we can add it.

**Comment by monsta** [comment]
I still don't see why it should be a new plugin. Isn't it easier to port the existing one to udisks2?

**Comment by info-cppsp** [comment]
I'm not sure what you mean. If you take a look at the udisks2-plugin.c file, I have written the following as a comment:
Udisks2 plugin for the mate-sensors-applet

written by info@cppsp.de using the structure and code of the previous version
from above author

Is this then not a port by your definition?
I didn't write it from scratch and I'm not sure what gave you that idea.
Please clarify.

**Comment by monsta** [comment]
I meant adapting the existing udisks code to udisks2 instead of adding a new plugin.

**Comment by info-cppsp** [comment]
You mean to have only one plugin for both versions of udisks?
That is impossible. Well, that it isn't, but I would think that it would be unwise.
You see, the two udisks have very different dbus APIs.
I have also thrown out dbus-glib, which is as deprecated as udisks...
I also got rid of libatasmart, as it is no longer needed because of the new udisks2 API.
So if I were to put support for both udisks into one plugin, it would be quite messy.

**Comment by monsta** [comment]
No, have one plugin for udisks2, adapted from existing udisks plugin.

**Comment by info-cppsp** [comment]
You are going to have to draw a picture, because now I am really confused...
This is what happened:
progress

**Comment by raveit65** [comment]
> I still don't see why it should be a new plugin. Isn't it easier to port the existing one to udisks2?

Again, fedora ships boths plugins and the old one displays more values with  d-feet Gui.
This should be reason enough.
We can drop the old one later if there is really no distro who ships udisk.
That linuxmint ships only the new one isn't sufficient for me.

**Comment by info-cppsp** [comment]
Oh, so he just meant to drop the old udisks plugin entirely?
I agree with you, it should be kept for backward compatibility.

**Comment by info-cppsp** [comment]
Not to be rude or anything - just to prevent misunderstandings - I consider discussing the deprecation of an old plugin off topic.
AFAIK this PR should be about my plugin, which has been written to address a feature request.
Please review this PR accordingly and let us discuss the old plugin in a separate issue.
Sorry, thank you.

**Comment by raveit65** [comment]
@sc0w @lukefromdc 
Could you please review the PR?

**Comment by info-cppsp** [comment]
Thanks for the review!

**Comment by info-cppsp** [comment]
OFF: I've made this PR about a month ago. May I make the next one or should I wait for this to be merged?

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-sensors-applet/commit/a7e24a66b69f02106db00e5392b68c39f5d4eb59
https://github.com/mate-desktop/mate-sensors-applet/commit/b46d8ac24d38b4b1a099fcc237f06ec5d3becfda
merged
Sorry for delay, i was bussy with other things the last weeks.
Thanks for your patient.

**Pull request closed without merging**
