### PR TITLE
Fix popup shower on removed HDD

### LINKED ISSUE #62: applet doesn't update sensorlist if a drive is removed from system
#### Expected behaviour
Sensor-list in preferences should be updated if a drive doesn't exists any more.

#### Actual behaviour
Sensor-list shows non-existent drives in preferences and if this sensor is enable we see a lot of popup warnings.

#### Steps to reproduce the behaviour
1. plug in an USB-drive
2. reload panel or applet
3. activate the temp sensor of this drive in applet 
4. unmount and unplug usb-drive
5. reload applet or panel
6. enjoy frequently popup warnings

#### MATE general version
master branch, 1.19.x

#### Package version
master branch, 1.19.1

#### Linux Distribution
fedora 26 with Mate developer version

#### Link to downstream report of your Distribution
not relevant

Problem exists since we use a gsettings key to store sensor order.
https://github.com/mate-desktop/mate-sensors-applet/commit/c5bce79ac7c654716cd8e1d69882a67053d469ef

The applet should be check for existing sensors with every start to update sensor-list, or better a frequently check for catching new pluged in usb-, e-sata- or other drives.
@info-cppsp 
Can you please take a look at this?

### PR DESCRIPTION
**Pull request by info-cppsp**
Added timer to active sensors, to suppress infinite popups, when a drive is removed from the system, with its sensor still active in msa.
fixes #62

### CODE REVIEW

**Comment by info-cppsp** [comment]
This is a quick fix to #54 
It seems I'll have to revisit the issue as it made things worse. :(

**Comment by raveit65** [comment]
Thanks

**Comment by info-cppsp** [comment]
maybe add it to 1.18 as well.

**Comment by raveit65** [comment]
good idea, i needed to do all by hand again as 'git cherry-pick' failed.
But i was able to add your name and commit date again.
https://github.com/mate-desktop/mate-sensors-applet/commit/b3fb40e7caae0ee8a60b36bdee3dd173a40f3463

**Pull request merged**
