### PR TITLE
fix some deprecations

### PR DESCRIPTION
**Pull request by raveit65**
Please test.
Mainly this is  a port to GtkGrid + disable annoying horizontal scrolling in prefs dialog.

Note, using gdk_rgba_parse doesn't fix broken colored graphs.

### CODE REVIEW

**Comment by monsta** [comment]
Hmm... I wonder how to do that while content isn't expanded yet :confused:

**Comment by raveit65** [comment]
@monsta 
???
You mean the GtkTreeView in sensor GtkNotebook tab?
Right from the treeview are buttons, how do you want expand something?
Or do you mean the preferences window of one sensor?
If yes, i am not sure if it is a good idea to expand a GtkSpinButton, btw. i don't think that it looks nice.

**Comment by monsta** [comment]
Yes, the treeview in the notebook. After https://github.com/mate-desktop/mate-sensors-applet/commit/f8f00fc49266ca69aaf5ac4544a509faa945839b it's expanded to the right when I click on the expander arrow to show the content:

sensors-1

sensors-2

So, the first column is resized because of name length, and then the whole dialog expands to the right at that moment. I would like it to expand when it's shown for the first time (i.e. when the treeview content isn't expanded yet). Not sure if it's possible or not.

**Comment by raveit65** [comment]
Ok, now i see what you mean :-)
I think the GtkExpander does the same like before, it increases the horizontal size of the first column if needed.
But w/o "hscrollbar-policy", GTK_POLICY_AUTOMATIC, the size of the whole window will increased.
I guess to avoid this was the reason why it was used here.
Maybe it's possible to set a minimum horz size for the whole treeview, but i think i will simply revert this commit.
To much work for a minimal improvement.

**Comment by monsta** [comment]
I agree, let's keep it as is for now.

**Comment by monsta** [comment]
Houston, we have a problem: https://github.com/mate-desktop/mate-sensors-applet/issues/41 :slightly_frowning_face:

**Comment by raveit65** [comment]
a problem other people ?  :-)

**Comment by lukefromdc** [comment]
I can confirm this exists but I never noticed it before as in my layout it is right next to the workspace switcher, which uses almost all vertical space in the panel itself.  Cpufreq-applet is next to it though so if I look closely the vertical offset to the top of the panel for both the text and the icons in the sensors applet becomes obvious

**Pull request merged**
