### PR TITLE
i45 fix graphs invisible

### PR DESCRIPTION
**Pull request by info-cppsp**
#45 fix, see comment there.

### CODE REVIEW

**Comment by raveit65** [comment]
Thx, the graphs are colored yet, but i don#t know if the graph do really update.
If i hover with the mouse over the applet i noticed that the grapfs changing.
But not if i don't hover.
Not sure if this is related to PR as i never used the graph for displaying sensor values.

**Comment by raveit65** [comment]
Opps, i noticed that the graph update after i closed preferences.   lol

**Comment by info-cppsp** [comment]
If you add a new msa to mate-panel, change the display quickly to graph and add sensors, you can at least see that the graphs are moving to the left.
Drive temperature isn't normally a fast changing value, so I would recommend keeping an eye on the msa on computer start. Still, as display height is < 24 pixels bc of the mate-panel and the temp interval is 20-60 (?), you may not see much of a change in the graph for 1-2 degrees temp change.
OR you could use a hair drier / heat gun on a drive. LOL

**Comment by raveit65** [comment]
it displays the changes well now without using a hair drier :-)
I seems that if the preferences window of the applet is open than the graphs wouldn't update.
Btw. only if you hover with the mouse over the applet.
Looks like a weird focus/backdrop effect.
But it is all fine if i close the preferences window.

**Comment by info-cppsp** [comment]
well, obviously if you divide a number between 0 and 1 with 65k, you are going to be close to zero, which in this case is black. on a black background...
the color gradient helps a bit, adding 0.4 to all colors, making the top gray.

**Comment by monsta** [comment]
I confirm the issue with graphs not moving when preferences window is open, at least with GTK+ 3.22. But it seems to be a separate issue, this PR only brings back the colors.

**Comment by info-cppsp** [comment]
I see that as well. But as probably no one is going to leave the pref-dialog open for too long, I would say it is not that critical, so 'won't fix'. What do you think?

**Comment by lukefromdc** [comment]
No reason to hold this PR over a separate issue like the prefs window holding the graph still while open, that can be another fix later

**Comment by raveit65** [comment]
Thanks.

**Comment by monsta** [comment]
I agree, we can fix the prefs window issue later. Thanks for this fix :slightly_smiling_face:

**Pull request merged**
