### PR TITLE
Drop aticonfig plugin

### PR DESCRIPTION
**Pull request by rbuj**
```
plugins/aticonfig/aticonfig-plugin.c:51:12: style: Unused variable: temp [unusedVariable]
    double temp;
           ^
plugins/aticonfig/aticonfig-plugin.c:52:9: style: Unused variable: read_count [unusedVariable]
    int read_count;
        ^
```

### CODE REVIEW

**Comment by raveit65** [comment]
Any chance to post which warning you did removed here, in other PRs and for the future?
This would help a lot when search in logs.

**Review by raveit65 — APPROVED** [review]
Warning is gone in cpp log.
I don't have an old ati device, so i can't really test it.
I suggest to remove this EOL plugin for old and unsupported hardware by AMD (ATI).
I am  in doubt that it will work with actual `amdgpu` driver.

**Comment by rbuj** [comment]
@raveit65 done

**Review by raveit65 — APPROVED** [review]
LGTM.

**Comment by lukefromdc** [comment]
My AMD graphics card (currently with AMDGPU) temp sensor shows up in the i2c-sys list of temperatures, voltages, fan speeds, etc. The list of supported interfaces in README does not even include this plugin. A startpage (privacy search engine) search for the string "ATIconfig" brings up references to the old and (I think no longer supported) fglrx proprietary driver for older ATI/AMD cards. Not likely MATE 1.26 (next stable release) would ever be released in the same version of any distro as fglrx unless someone's LTS is following current MATE versions.

Since this plugin is for fglrx, removing it should have no effect on user of the radeonSI,  r600, and older AMD open source graphics kernel drivers.

**Review by lukefromdc — APPROVED** [review]
Build completes fine with no surprises (like what an error in the build system changes could cause. On installation behaves exactly the same as master with the AMDGPU driver.

**Pull request merged**
