### PR TITLE
port to in-process for wayland support

### PR DESCRIPTION
**Pull request by lukefromdc**
Wayland cannot use xembed/GtkPlug/GtkSocket so port to in-process. The applet then works on wayland.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Tested with Wayfire and with compiz in x11, same apparent behavior in both and as before (in x11-only). I am in the process of porting to in-process all the applets save those that truly require x11 at this point (show desktop, workspace switcher, tray side of notification area though sni works).

This will yield a full-featured mate-panel that works in both x11 and in wayland compositors supporting gtk-layer-shell, which will possibly be one of the best wayland panels and thus find use outside of MATE as well as in a future MATE wayland session.

Distros are starting to talk of transitioning out of even offering x11 so we need to make wayland work. Wayfire is a lot like compiz so a mate-wayfire session will be immediately familiar to GNOME 2/compiz fans

**Comment by raveit65** [comment]
Applet runs fine with X11. Sorry, i don't have a wayland session with Mate running.
As i compiled applets from mate-panel itself  with in in-process for fedora i won't asked for an option to select in-process in configure like it is possible with mate-panel package ;)
Personal i hope X11 will stay in distros the next 50 -100 years. I never heard in Fedora or RedHat based distros that someone thinks about setting X11 to eol.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by lukefromdc** [comment]
There has been some preliminary discussion on phoronix.com about sunsetting x11, coming from the devs of a specialized linux distro for Apple hardware. Lost track of the story, cannot search for it easily as Phoronix uses Google (which I ban from my systems) for their search backend

**Comment by raveit65** [comment]
It's already merged, but can we have an option to build in-process/out-of-process, similar what you did for mate-media?
When you have some free resources....

**Comment by lukefromdc** [comment]
I will put that on the agenda

**Pull request merged**
