### PR TITLE
Add NetBSD support.

### PR DESCRIPTION
**Pull request by jaredmcneill**
This patch adds support for NetBSD’s envsys(4) sensor API.

### CODE REVIEW

**Comment by raveit65** [comment]
> Tested on arm64 and amd64

and broken or what? :)

**Comment by nbyouri** [comment]
It works well 👍

**Comment by raveit65** [comment]
I do not use bsd, normal building in a RPM for fedora without `--enable-netbsd` works fine.
Also creating a new tarball with `make discheck` works well.
I see no different to other plugins like `libsensors` only that `envsys` sensors is used by bsd only.
So, I am fine with adding this plugin as we support BSD.

**Comment by nbyouri** [comment]
Any news? We'd like to see this merged !

**Comment by monsta** [comment]
If we merge it, we won't be able to maintain it, even build it.

We actually have a library for building plugins externally:
```
$ ls -l /usr/include/mate-sensors-applet/
итого 8
-rw-r--r-- 1 root root 3199 фев 28 11:24 sensors-applet-plugin.h
-rw-r--r-- 1 root root 1769 фев 28 11:24 sensors-applet-sensor.h
```
```
$ ls -l /usr/lib/x86_64-linux-gnu/libmate-sensors-applet-plugin.*
lrwxrwxrwx 1 root root    38 фев 28 11:24 /usr/lib/x86_64-linux-gnu/libmate-sensors-applet-plugin.so -> libmate-sensors-applet-plugin.so.0.0.0
lrwxrwxrwx 1 root root    38 фев 28 11:24 /usr/lib/x86_64-linux-gnu/libmate-sensors-applet-plugin.so.0 -> libmate-sensors-applet-plugin.so.0.0.0
-rw-r--r-- 1 root root 10080 фев 28 11:24 /usr/lib/x86_64-linux-gnu/libmate-sensors-applet-plugin.so.0.0.0
```
It lacks a `.pc` file though, we can add it if needed.

**Comment by raveit65** [comment]
Well, maintaining the code is a problem and we had some bad experience in the past with adding foreign code to our repos.
People say the want to maintain it, but they didn't after we add the code. :/
For this reason i won't powering such a process any more.

**Comment by muktupavels** [comment]
Does this has to be separate plugin? For example I see there is `hddtemp` plugin and looking in merge request I see that `netbsd` plugin also has temperature sensor and icon for hdd...

Would not it make sense to add NetBSD support into existing plugins?

**Comment by nbyouri** [comment]
I maintain all components of MATE for NetBSD, this means I will take care of this code that @jaredmcneill  wrote.

**Comment by monsta** [comment]
It makes sense to make this a separate plugin because it's only for one OS. We even won't be able to build it on Linux.

**Comment by monsta** [comment]
Can you try building this plugin externally? If something else is needed for it, we can add it.

**Comment by raveit65** [comment]
unsuscribe

**Comment by raveit65** [comment]
We have other packages too where we have bsd code which we can test for our self, eg. mate-screensaver.
Bsd maintainer @nbyouri  promised to have a look at it and can check if the plugin is working.
And it doesn't affect a normal build with linux.
In the end we are free to drop code when it doesn't work anymore in future.
Btw. all that AMD/ATI code is still obsolete and broken since years, and nobody cares about ;)
So, i don't see any reason not adding a working plugin for a distro which we official support, see mate-user-guide.
@monsta  i hope you can agree.

**Comment by raveit65** [comment]
No answer, so i assume everybody is fine with it.

**Pull request merged**
