### PR TITLE
active-sensor.c: Fix build warning:

### PR DESCRIPTION
**Pull request by sc0w**
Fixes the build warning: "iteration 2 invokes undefined behavior"

### CODE REVIEW

**Comment by sc0w** [comment]
@lukefromdc you can't see the build warning without the PR?

I see:

```
active-sensor.c: In function ‘active_sensor_new’:
active-sensor.c:425:44: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
         active_sensor->alarm_timeout_id[i] = -1;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
active-sensor.c:424:5: note: within this loop
     for (i = 0; i < NUM_NOTIFS; i++) {
     ^~~
```

The PR fixes the build warning here

**Comment by lukefromdc** [comment]
It was WITH the PR that I did not get any build warnings, but I really don't have a clear understanding of what's going on here and why we are getting that one. I didn't check the build warnings from master before rebuilding with the changed file-and in a whole package build there are still so many warnings on most of our packages.

This one looks from the warning like the loop itself works fine, but sets -1 active_sensor->alarm_timeout_id[i] = -1 with some optimization conditions.  I am assuming that's the one this PR fixes? The way you wrote your comment I thought you were saying the undefined condition was new to this PR

**Comment by sc0w** [comment]
> The way you wrote your comment I thought you were saying the undefined condition was new to this PR

no, I edited the first comment and the commit message, I hope now it is understandable :)

**Comment by info-cppsp** [comment]
please have a look at the _ActiveSensor struct in active-sensor.h
it has:
`gint alarm_timeout_id[NUM_ALARMS];`
so please rewrite the for to:
`for (i = 0; i < NUM_ALARMS; i++) {`
let me try...

**Comment by sc0w** [comment]
@info-cppsp ok, done

**Comment by raveit65** [comment]
Confirmed, this warning exists beside tons of other warnings.

**Comment by raveit65** [comment]
Guys, my new mobo is to new for lm_sensors, the applet don't display any sensor for mobo and cpu any more. I can only test the function of udisks and nvidia gpu sensors.
So, this should be merge by someone who can do full test.
For me build warnings are a bug fix and translations aren't affected, in result the freeze can be ignored in this case.

**Comment by monsta** [comment]
Yeah, `NUM_ALARMS` is 2 while `NUM_NOTIFS` is 3, so the 2nd iteration might write -1 to the next struct field, `alarm_command`. Luckily, this happens in the "constructor" function, and `alarm_command` is actually initialized later anyway. But of course it's good to fix this.

**Pull request merged**
