### PR TITLE
Remove deprecated udisks plugin

### PR DESCRIPTION
**Pull request by info-cppsp**
udisks and dbus-glib have been deprecated for at least 5 years.
Linux Mint 17.3 and therefore Ubuntu 14.04 LTS ship with udisks2 as default.
I've also made a new plugin for udisks2.
Let's just get rid of this, shall we?

### CODE REVIEW

**Comment by monsta** [comment]
Well... there was a discussion at https://github.com/mate-desktop/mate-sensors-applet/pull/50#issuecomment-329877068...

**Comment by info-cppsp** [comment]
Right. Now I remember.
I would say if any other thing is needed (other than HDD temperature), I am going to try to build it into the new plugin.
Also this PR gives the team a chance to vote on this, but what @raveit65 mentioned doesn't seems to be a that compelling reason to keep it.

**Comment by raveit65** [comment]
It seems that old udisk plugin can only be used in recent fedora version.
It is already removed from rhel7 since 2 years or so.
No idea why it isn't removed from fedora, maybe it is forgotten....
But if all agree we can drop it before release.
@monsta  OK ?

**Comment by sc0w** [comment]
udisks 1 was removed from debian sid and testing in Jun 2015 with the reason: "dead upstream, replaced by udisks2"

btw, this PR have conflicts

**Comment by info-cppsp** [comment]
right, let me force push...

**Comment by raveit65** [comment]
Yes, udisk2 plugin won't build anymore.

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/mate-sensors-applet/pull/74

**Pull request merged**
