### PR TITLE
build: enable udisk2 plugin again

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by raveit65** [comment]
As a suggestion by @info-cppsp i removed checks in configure for libsmart and dbus-glib for udisk2 plugin.
PR is updated.

**Comment by info-cppsp** [comment]
I have tested this, and for me, it works.

**Comment by monsta** [comment]
I'm not sure about libatasmart - there's a large block of commented code using it. Is it the old code from udisks plugin that was used to refresh the info? I remember we had the problem of slow refreshing (about 10 minutes) in udisks2 plugin...

**Comment by info-cppsp** [comment]
I have left the old udisks code in the new plugin for comparison, info and so on.
I guess one day I'm gonna remove it.
BUT there is nothing left using libatasmart, especially in the udisks2 plugin.

The slow refresh is because of udisks2.
udisks has a refresh of 30 mins...

also:
'there's a large block of commented **out** code using it'
u wut m8? :P

**Pull request merged**
