### PR TITLE
prefs-dialog: use hscrollbar-policy GTK_POLICY_NEVER

### PR DESCRIPTION
**Pull request by raveit65**
fixes https://github.com/mate-desktop/mate-sensors-applet/issues/76

@info-cppsp @monsta 
Please test

### CODE REVIEW

**Comment by monsta** [comment]
Hmm... this change was first included in https://github.com/mate-desktop/mate-sensors-applet/pull/40, but after some discussion, the commit was removed from that PR before merging.

**Comment by info-cppsp** [comment]
another solution would be to place the enabled column first. (or second)

**Comment by raveit65** [comment]
Please test again, i don't see any columns jumping any more with my locale.
Maybe we should increase columns min-size a bit for other languages with long words ?

**Comment by info-cppsp** [comment]
I like the first commit only better, as the prefs dialog is packed nice and small. (like before)
It only grows bigger if you open the sensor tree.
With the new commit it starts bigger.
But that's just me. Otherwise it is working.

**Comment by raveit65** [comment]
well, 
without 'gtk_tree_view_column_set_min_width(prefs_dialog->enable_column, 80);'
the text of the colum button can be cut off in some languages.
Eg. in german you see only 'aktivi' instead of 'aktivieren. I guess this can be a problem with other locale too.
So this line is a should be for me.
The other changes i did for satisfy @monsta 
This is recommended for me.
Guys, can you please find a consensus?

**Comment by info-cppsp** [comment]
I didn't object, I just shared my opinion.
screenshot at 2018-02-18 17-45-30

BTW what about this space? kinda looks weird
does it look like this for you too?

**Comment by info-cppsp** [comment]
screenshot at 2018-02-18 18-59-05

this is how making enabled the first column looks like... (w/o this PR)

**Comment by info-cppsp** [comment]
"without 'gtk_tree_view_column_set_min_width(prefs_dialog->enable_column, 80);'
the text of the colum button can be cut off in some languages."

screenshot at 2018-02-18 19-06-26

I'm not sure why that happens, but if I just write a long string, w/o the _() translation function, the column extends normally.
```c
gtk_tree_view_columns_autosize(prefs_dialog->view);
```
is used for the treeview, so...

**Comment by lukefromdc** [comment]
The last changes work fine here in most themes, though the last character in "Enabled" gets cut off in ContrastHighInverse with the larger bold font. Can't test other languages as I purge unused locales for space

**Comment by raveit65** [comment]
> I'm not sure why that happens, but if I just write a long string, w/o the _() translation function (edit: even with _()), the column extends normally.

Because of the v-scrollbar, in gome gtk+ use overlay- scrollbars, so they doesn't have this problem.

**Comment by raveit65** [comment]
> BTW what about this space? kinda looks weird
does it look like this for you too?

Is this with a linuxmint theme?
I am not really sure if mint-themes support gtk+-3.20/22.
With our default theme (Menta) or any other from MATE i don't see the space.
msa-pref-dialog

**Comment by raveit65** [comment]
I fixed the issue in ContrastHighInverse with the larger bold font.
With using
```
gtk_tree_view_column_set_min_width(prefs_dialog->enable_column, 90); 
```
msa-prefs-dialog-hci

With an alternative patch from here https://gist.github.com/raveit65/d2a44be228f3138614bcc3ad4381a97c
i set only the min-size for the enable_column
msa-prefs-dialog-1
msa-prefs-dialog-2
msa-prefs-dialog-3
As you can see, with opening the expander for udisk plugin the weight of the whole window will increased now, because of larger width of label_column.
Personal, i can live with both patches, mainly i wanted to disable the annoying h-schrollbar.

**Comment by raveit65** [comment]
Ok , i can reproduce the space issue with m-s-a from master if i use english language.
msa-prefs-dialog-space
So, the real cause for this problem doesn't  come from this PR.
I am looking for an option in GtkGrid to fix this.

**Comment by raveit65** [comment]
Last commit fixes the cut-off problem of enable_column in a better way.
Thanks to @monsta 
But the resizing + space issue is still left.
Branch is rebased.

**Comment by raveit65** [comment]
Branch is rebased again as previous suggestion for autosize column doen#t work with ContrastHighInverse theme and my locale.
But i could fix the space issue with the general tab.

**Comment by monsta** [comment]
Yeah, the problem with vertical scrollbar wasn't solved after all... I was able to reproduce it myself:

bad-scrollbar

The scrollbar does the wrong thing and draws over the column header.
It's fixed now with setting minimum column width (again), though I don't know if it's enough for every language.

**Comment by lukefromdc** [comment]
I just retested, and still got the scrollbar drawn over the end of the last button in ubuntustudio_legacy. None of the default MATE themes nor Adwaita were affected, but this could point to issues in other languages, larger fonts, etc.

**Comment by raveit65** [comment]
So, only the **resizing the whole window when using the expanders** is left as issue.
I can fix that with increasing the min-size of the columns.
```
diff --git a/sensors-applet/prefs-dialog.c b/sensors-applet/prefs-dialog.c
index 099dff8..4c4b855 100644
--- a/sensors-applet/prefs-dialog.c
+++ b/sensors-applet/prefs-dialog.c
@@ -772,7 +772,7 @@ void prefs_dialog_open(SensorsApplet *sensors_applet) {
                                                                        "text", ID_COLUMN,
                                                                        NULL);
 
-    gtk_tree_view_column_set_min_width(prefs_dialog->id_column, 90);
+    gtk_tree_view_column_set_min_width(prefs_dialog->id_column, 150);
 
     prefs_dialog->label_column = gtk_tree_view_column_new_with_attributes(_("Label"),
                                                                           prefs_dialog->label_renderer,
@@ -780,7 +780,7 @@ void prefs_dialog_open(SensorsApplet *sensors_applet) {
                                                                           "visible", VISIBLE_COLUMN,
                                                                           NULL);
 
-    gtk_tree_view_column_set_min_width(prefs_dialog->label_column, 100);
+    gtk_tree_view_column_set_min_width(prefs_dialog->label_column, 135);
 
     /* create the tooltip */
     gtk_widget_set_tooltip_text(GTK_WIDGET(prefs_dialog->view),
-- 
2.13.6
```
But this will increase also the general width of the window and the width can be to small if disks use a large label.
Maybe , we should ignore this last issue?

**Comment by lukefromdc** [comment]
We could ignore that, any theme that has this issue can fix it there. We can revisit it if we get complaints from users of other languages

**Comment by info-cppsp** [comment]
I have tested the 3 commits with my brand new dummy plugin on ub 18.04.
works with all themes

The dialog gets bigger when expanding a plugin, but that is OK! You can leave it as is.

**Pull request merged**
