### PR TITLE
sonypi-plugin.c: Make sonypi plugin portable to GNU/Hurd

### PR DESCRIPTION
**Pull request by flexiondotorg**
Taken from a downstream Debian patch.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Do we have anyone here who can test this in use? I have neither a Sony anything nor anything running the Hurd kernel. If not we will have to rely on Debian having tested it and just ensure we don't break anything else.

**Comment by muktupavels** [comment]
Are not both `unsigned char` typedefs?

**Comment by monsta** [comment]
They are, so it should work as before. I wonder why `guint8` might break the build though...  it's a type from GLib, isn't the library the same for all architectures?

@sunweaver: did it actually break the build before you added the patch...?

**Comment by raveit65** [comment]
I don't have the hardware to test this.

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Any news on this?
Is this save to merge?

**Pull request merged**
