### PR TITLE
Sync with sensors applet

### PR DESCRIPTION
**Pull request by infirit**
Sync up with most of sensors-applet. There is some code that adds GSettings to sensors-applet but this was not trivial so left for another time.

Compiles and runs nicely here (intel gfx) but needs testing on ati/nvidia hence this PR.

### CODE REVIEW

**Comment by monsta** [comment]
Wow, that's a big one. I have nvidia (with proprietary drivers), so I can test it later.
BTW, what mbmon is for?

**Comment by monsta** [comment]
@NiceandGently @flexiondotorg @stefano-k 
please help with testing too if you can :smile:

**Comment by infirit** [comment]
[mbmon](http://www.nt.phys.kyushu-u.ac.jp/shimizu/download/xmbmon/README-xmbmon200.html) is just another monitoring tool like libsensors. It applied cleanly so I thought why not :smile:

**Comment by monsta** [comment]
I actually wondered what it might monitor :smile:

**Comment by infirit** [comment]
>I actually wondered what it might monitor

I may misunderstand this but the chips/HW supported are listed in the readme linked.

**Comment by monsta** [comment]
About ```mbmon``` - are you sure it's needed? Looks like this tool isn't maintained since 2008. It might not even have any support for the motherboards released since then. I think ```lm-sensors``` pretty much obsoletes this.

**Comment by monsta** [comment]
About nvidia stuff: new "thermal" sensor shows exactly the same value as the old "core" one - is that by design?
Also I noticed that the fan speed is shown in RPMs - but ```nvidia-settings``` tool says reading RPMs is unsupported and the value is actually in percents:

nvidia x server settings

**Comment by infirit** [comment]
I only brought the code in sync with the original applet so that new fixes and feature can be easily applied. The questions are in such a detail that I do not know without spending significant effort to figure out (which I have no time for).

re mbmon, it is self contained and does not break anything. Plus the original applet authors considered it useful so who are we to argue against it :smile:. Do you care strongly?

**Comment by NiceandGently** [comment]
hmm, last xmbmon is from 2005
http://www.nt.phys.kyushu-u.ac.jp/shimizu/download/xmbmon/
Is this really shipped by any distro?

**Comment by NiceandGently** [comment]
gtk3 build failed with nvidia!
```
Making all in nvidia
make[2]: Entering directory '/builddir/build/BUILD/mate-sensors-applet-1.10.2/plugins/nvidia'
  CC       nvidia-plugin.lo
nvidia-plugin.c: In function 'nvidia_plugin_get_sensor_value':
nvidia-plugin.c:55:9: error: 'NV_CTRL_TARGET_TYPE_THERMAL_SENSOR' undeclared (first use in this function)
         NV_CTRL_TARGET_TYPE_THERMAL_SENSOR,
         ^
nvidia-plugin.c:55:9: note: each undeclared identifier is reported only once for each function it appears in
nvidia-plugin.c:58:9: error: 'NV_CTRL_THERMAL_SENSOR_READING' undeclared (first use in this function)
         NV_CTRL_THERMAL_SENSOR_READING,
         ^
nvidia-plugin.c:62:9: error: 'NV_CTRL_TARGET_TYPE_COOLER' undeclared (first use in this function)
         NV_CTRL_TARGET_TYPE_COOLER,
         ^
nvidia-plugin.c:65:9: error: 'NV_CTRL_THERMAL_COOLER_LEVEL' undeclared (first use in this function)
         NV_CTRL_THERMAL_COOLER_LEVEL,
         ^
nvidia-plugin.c: In function 'nvidia_plugin_init':
nvidia-plugin.c:117:10: error: 'NV_CTRL_TARGET_TYPE_THERMAL_SENSOR' undeclared (first use in this function)
          NV_CTRL_TARGET_TYPE_THERMAL_SENSOR,
          ^
nvidia-plugin.c:136:10: error: 'NV_CTRL_TARGET_TYPE_COOLER' undeclared (first use in this function)
          NV_CTRL_TARGET_TYPE_COOLER,
          ^
Makefile:502: recipe for target 'nvidia-plugin.lo' failed
make[2]: Leaving directory '/builddir/build/BUILD/mate-sensors-applet-1.10.2/plugins/nvidia'
Makefile:433: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/builddir/build/BUILD/mate-sensors-applet-1.10.2/plugins'
Makefile:563: recipe for target 'all-recursive' failed
make[2]: *** [nvidia-plugin.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by infirit** [comment]
Yes distros schip mbmon on linux. And do note that MATE runs on other os's like *bsd  where lmsensors is not available.

I will look at the build failure when I am back at home next week.

**Comment by NiceandGently** [comment]
> Yes distros schip mbmon on linux. And do note that MATE runs on other os's like *bsd where lmsensors is not available.

Ok, bsd is a reason.

**Comment by monsta** [comment]
> gtk3 build failed with nvidia!

Probably it's some old version of ```libxnvctrl```...

**Comment by monsta** [comment]
> And do note that MATE runs on other os's like *bsd where lmsensors is not available.

Poor BSD users... how did they even use this applet then? lm-sensors is a significant part.

**Comment by NiceandGently** [comment]
> Probably it's some old version of libxnvctrl...

I can only use this version http://pkgs.fedoraproject.org/cgit/libXNVCtrl.git/log/
Since f14  libXNVCtrl isn't update anymore, only rebuild.
But i maintain it for epel7 branch, so patches are welcome ;)

**Comment by monsta** [comment]
Damn, version 169 is ancient... Ubuntu 14.04 has 331 (it's in ```nvidia-settings``` package there).

**Comment by NiceandGently** [comment]
......and nvidia-settings is nonfree

**Comment by monsta** [comment]
That's not a problem for Mint :smile:
As for Debian/Ubuntu, ```libxnvctrl``` has been split into a separate (and free) package in recent releases.
But anyway, this is not the point here :smile:

**Comment by infirit** [comment]
The nvidia plugin is for the non free driver anyway and will not work without it. While I sympathize with the old version in fedora the commit brings support for newer HW so it will need a newer version of ```libxnvctrl```.

I'll probably merge and push this in a day or two.

**Comment by NiceandGently** [comment]
It would be friendly to wait for merging it.
I need to contact main fedora maintainer to see if it's possible to update libxnvctrl for fedora.
Also mate-sensor-applet isn't the own package which depends on it, so another maintainer is involved too.
```
root@mother rave]# repoquery --whatrequires libXNVCtrl
hwloc-plugins-0:1.10.1-2.fc22.x86_64
mate-sensors-applet-0:1.10.2-1.fc22.x86_64
```
All this action is impossible to do in one or two days.
If it's not possible to update the package i can't build mate-sensor-applet with nvidia sensor, which is a regression imo.

**Comment by NiceandGently** [comment]
Which nvidia-settings version is needed?
Latest is nvidia-settings-352.21.tar.bz2
see ftp://download.nvidia.com/XFree86/nvidia-settings/

**Comment by infirit** [comment]
>All this action is impossible to do in one or two days.

You have till the next MATE release to get this lib updated in fedora, this is not meant to go into 1.10 which should only get bugfixes now. Good enough?

>Which nvidia-settings version is needed?

I build against 343.22 so and I think @monsta build against ~340 which is in jessie.

**Comment by NiceandGently** [comment]
> You have till the next MATE release to get this lib updated in fedora, this is not meant to go into 1.10 which should only get bugfixes now. Good enough?

good enough, so m-s-a needs branched.
Another question is does that work with current legacy nvidia driver versions?
304 and 340.

**Comment by leigh123linux** [comment]
@NiceandGently 

This is going to cost you some more reviews :laughing:  https://dl.dropboxusercontent.com/u/6907158/libXNVCtrl-352.21-1.fc23.src.rpm

**Comment by infirit** [comment]
>Another question is does that work with all current legacy nvidia driver versions

tbh, I don't know but.. nvidia-settings does not mention anything on this subject so I think it is likely backwards compatible.

**Comment by NiceandGently** [comment]
RFE is filed out.
https://bugzilla.redhat.com/show_bug.cgi?id=1240234

**Comment by monsta** [comment]
I can say it builds fine in Mint 17.2 (based on Ubuntu 14.04) with ```nvidia-settings``` 331.20, and of course in Debian Jessie where we have ```libxnvctrl``` 340.46.

**Comment by monsta** [comment]
Ok, found out the exact versions where these two defines appeared:

```NV_CTRL_THERMAL_COOLER_LEVEL``` - 190.32:
https://github.com/NVIDIA/nvidia-settings/commit/29bde128727f8b9d5cf9415265ba8b20ffc89944#diff-c8d9162ce179db35fb13e3b489e36facR2577
```NV_CTRL_THERMAL_SENSOR_READING``` - 256.25:
https://github.com/NVIDIA/nvidia-settings/commit/9f277148255d8d2f4e7970e8d13d1f77068dbed9#diff-c8d9162ce179db35fb13e3b489e36facR2916

**Comment by monsta** [comment]
> Also I noticed that the fan speed is shown in RPMs - but ```nvidia-settings``` tool says reading RPMs is unsupported and the value is actually in percents

Turned out it's a limitation of the applet's own code.
All values received from fans are treated as RPMs:
https://github.com/mate-desktop/mate-sensors-applet/blob/master/sensors-applet/active-sensor.c#L625
https://github.com/mate-desktop/mate-sensors-applet/blob/master/sensors-applet/sensors-applet.c#L372
https://github.com/mate-desktop/mate-sensors-applet/blob/master/sensors-applet/sensors-applet.h#L57
Limits are also set for RPMs:
https://github.com/mate-desktop/mate-sensors-applet/blob/master/lib/sensors-applet-plugin.c#L89

**Comment by NiceandGently** [comment]
OK, i tested again and added the new patch.
On my main box with proprietary nvidia driver:
GTK2/GTK3 build works well.
On my notebook with hybrid grapphics (intel + nvidia), but intel is in used.
Same gtk2 build failed, means i can't add the applet to the panel.

**Comment by NiceandGently** [comment]
commit 1 is good --> applet starts on my notebook
commit 2 breaks the start of the applet on my notebook
commit 3 didn't apply when only using commit 1 + 3

**Comment by infirit** [comment]
Thanks for testing. I merged all the good commits and the 3rd. It looks like you are hitting one of the g_debug's that @monsta and I do not. I'll close this one now and try to figure out what is going on.

**Comment by NiceandGently** [comment]
@infirit 
libXNVCtrl is updated in fedora + epel7 branch (rhel7 family)
https://admin.fedoraproject.org/updates/libXNVCtrl-352.21-1.fc22?_csrf_token=bf4cb00b505fa46daa5f85dd006dd067b7481cfd
I agree if you want backport changes to 1.10 branch, would be nice to have new sensors.
Maybe you need to check the situation in other distros.

**Pull request closed without merging**
