### PR TITLE
Remove deprecated eee plugin

### PR DESCRIPTION
**Pull request by info-cppsp**
According to https://github.com/mate-desktop/mate-sensors-applet/pull/64#issuecomment-358425379 the eee plugin is obsolete, the same functionality is available through lm-sensors.

### CODE REVIEW

**Comment by info-cppsp** [comment]
Right.
Do you want the lines removed from the .po files as well?

**Comment by raveit65** [comment]
Too late, already done and merged ;-)
https://github.com/mate-desktop/mate-sensors-applet/commit/9a5fc1a315cd093563b493c35f521e0ec2621f4a

**Comment by raveit65** [comment]
@info-cppsp 
.po files don't needs updating by ourself.
I will create a new mate-sensors-applet.pot with 'make pot' in /po.
Than i upload the file to transifex.
In this case a very late upload to transifex doesn't matter.
But normally we should give translators time for translating new strings before we can release a new tarball.

**Comment by monsta** [comment]
That "FAN" string is used in other places too (see the comments in `.po` files), so there's no real change for the translators. So we can upload the updated `.pot` or leave it as is, it shouldn't affect anything.

**Comment by info-cppsp** [comment]
Yeah, got that figured out pretty fast, I even edited the comment.
But thanks for explaining.

**Pull request closed without merging**
