### PR TITLE
Fix indents

### PR DESCRIPTION
**Pull request by info-cppsp**
(updated PR)

went through all .c and .h files

removed trailing spaces
changed all indents to 4 spaces / indent level - no more tabs
made code more compact and alike
e.g.
```c
if () {
    /* */
} else {
    /* */
}
```

### CODE REVIEW

**Comment by info-cppsp** [comment]
Well, I made this mostly with reg replace and by hand.
What parts need more editing?

**Comment by raveit65** [comment]
@info-cppsp 
Can we split the commit in several small ones please ?
Maybe one commit for every folder or in any other kind of sort which makes sense.
I wouldn't pick more than 3 or 4 files for one commit, depends on their diff size.
One commit is really to big, especially if the commit causes a problem and we need to use 'git bisect' to find the culprit commit.

Btw. I saw you're at https://github.com/orgs/mate-desktop/teams/contributors/members  :-)
Would be nice to see you at icrc channel, this is our communication channel.

**Comment by raveit65** [comment]
> Well, I made this mostly with reg replace and by hand.
> What parts need more editing?

For example here https://github.com/mate-desktop/mate-sensors-applet/pull/58/commits/99ceaf453477a84b2f6c8aa1b526627276192f18#diff-edfe4b0dd14943ab919afe8d26f25371R109

But with smaller commits this would be easier to see.

**Comment by info-cppsp** [comment]
I took it apart. About four plugin files each, then the rest of the files.

Yes, thank you.
ok. It is much easier for me to have all the infos at a, issue or PR, so that I don't forget them.

What's wrong with that line? I am thinking about OOP, where that wouldn't be needed any more.

**Comment by raveit65** [comment]
Ok, that's better, but as it is a huge code change i would like to see a review from @monsta

**Comment by monsta** [comment]
It's too big to merge anyway. Let's start with small changes. If you see mix of tabs and spaces in some file, make it uniform. It it's mostly spaces, convert all to spaces. If it's mostly tabs, well, let's use tabs in that file for now.

**Comment by info-cppsp** [comment]
can you IRC now?

**Comment by clefebvre** [comment]
Looks good to me.

**Comment by raveit65** [comment]
> It's too big to merge anyway

@monsta 
Why it is to big?
One commit change not more than 4 files.
Do you really like to see one commit for every file?
If this PR causes a regression than we have 8 commits to find an issue with 'git bisect'.
Don't understand me wrong, but i like to understand understand your concerns.

**Comment by lukefromdc** [comment]
When an entire mate application's files mix tabs and spaces, a fix for all of them changing almost every file and is thus by definiation a big commit. Would be a real mess in the changelog to do this one file at a time

**Comment by raveit65** [comment]
I have the origin commit running since 8 days and i see not problems with it.
Now i will test the 8 single commits.

**Comment by info-cppsp** [comment]
https://stackoverflow.com/questions/16423024/how-can-i-diff-2-files-while-ignoring-leading-white-space
https://github.com/blog/967-github-secrets

diif has some CLI options to ignore white space. Some have been added to GitHub as well.
Though I can't guarantee that this PR is perfect, I have been through the diffs here twice already.

**Comment by raveit65** [comment]
merged, thank you
https://github.com/mate-desktop/mate-sensors-applet/commit/2921854dcc3148fcf7a28104f3992abf6bc98558
https://github.com/mate-desktop/mate-sensors-applet/commit/93dd9f3d232220ec4a807f122a9fae1e71f06f0f
https://github.com/mate-desktop/mate-sensors-applet/commit/03d94bc09168713cdc3f9d0a51539d4b8398ba0d
https://github.com/mate-desktop/mate-sensors-applet/commit/b678af6c09b45c7dd2488972ec78a8d86b34a206
https://github.com/mate-desktop/mate-sensors-applet/commit/287eeb06149861d8a56de73b2c897ebac95e48b0
https://github.com/mate-desktop/mate-sensors-applet/commit/e493e98f479c5559adfe2451b6c80bf87318149a
https://github.com/mate-desktop/mate-sensors-applet/commit/2c16ec3e88297515b75e429f52e0c0bd6703bab3
https://github.com/mate-desktop/mate-sensors-applet/commit/7f867152aa68b85547a693cd09985fcc8b359262

**Pull request closed without merging**
