### PR TITLE
GtkStock deprecated fix 1

### PR DESCRIPTION
**Pull request by info-cppsp**
Fix make warnings

### CODE REVIEW

**Comment by raveit65** [comment]
This will remove all icons from buttons, which is an indicator that you're using MATE.
For this reason we decided not to fix GtkStock and menuitems deprecations all over Mate, and we simply want to use them as long we don't switch to gtk4.

**Comment by info-cppsp** [comment]
OK. Please review the other changes then.

**Comment by raveit65** [comment]
Hmm, did you update the PR ?

**Comment by info-cppsp** [comment]
no, so far the changes are for the prefs and the sensor-conf dialog boxes.

For the GtkActionGroup, and msa menu
how about using 
https://developer.gnome.org/GMenu/
see Icons
Here is an example:
https://developer.gnome.org/gtk3/stable/GtkImageMenuItem.html

**Comment by raveit65** [comment]
I think you will remove the icons from menu too if you replace GtkActionGroup
But i am not sure, i never tried it for myself.
And i think we have to start first with mate-panel itself.
As far as i know it is done in gnome-panel , but here the icons are gone.
@monsta ^^^^^^^^
Btw. did you had an idea for https://github.com/mate-desktop/mate-sensors-applet/issues/62
I think this is really the biggest problem with m-s-a and we want to release Mate-1.20 end of this month.

**Comment by monsta** [comment]
This PR is all about removing icons from buttons, which we don't do.

**Comment by info-cppsp** [comment]
Wait, you mean, you see icons in the dialog boxes in the buttons??
screenshot at 2018-01-17 20-12-24
like here??

**Comment by monsta** [comment]
Of course

**Comment by info-cppsp** [comment]
wut?
I don't. :(
Not even with master and not even with stock mint 17.3 msa 1.12

BUT I think I can make icons in there, just tell me what you want.

What I can't do is fix the sensors-applet.c stuff. I would have to rewrite the mate-panel-applet library and the problem with that is that a mate-panel applet is not a GtkApplication, but a child from a GtkWidget. I have just about no idea how to put in a GtkBuilder to make a context menu instead of the ui_manager...
OR
If I had a way to not use the ui_manager automatically in msa...

**Comment by info-cppsp** [comment]
how about this?
screenshot at 2018-01-17 22-22-45

**Comment by raveit65** [comment]
The arrows and properties buttons are Ok on your screens.
Well, if you like to use a horzontal box inside the button with 2 childs or something like this , this is OK.
I did the same a while ago for a button in atril.
But avoid to remove the icons like with the help and close buttons in your screenshots.

**Comment by lukefromdc** [comment]
You can upload images but the embed breaks. Remove the ! to display the links

**Comment by info-cppsp** [comment]
OK, so there is a GSettings key:
/org/mate/desktop/interface/buttons-have-icons
In both mint 17.3 and 18.3 this key is not set and it defaults to false.
As this is a system wide setting, this means that on mint, the buttons don't have icons in them.

@clefebvre  @flexiondotorg 
Did you know about this?
Is this intentional?

-----
Local I had to add `gtk_button_set_always_show_image(prefs_dialog->sensor_up_button, TRUE);` to the up button to have the icon show up as is in the previous comment.
That essentially ignores the gsettings key value.

I have the up, down, properties buttons as they were before, but with new code, locally.
I have to find a way to add a GtkButton to a GtkDialog to fix the Help and Close buttons.

**Comment by info-cppsp** [comment]
[testdialog.c.txt](https://github.com/mate-desktop/mate-sensors-applet/files/1643699/testdialog.c.txt)

I have rewritten https://github.com/linuxmint/gtk/blob/master/tests/testdialog.c to play around with migrating the Help and Close buttons. See the show_dialog_with_buttons() function.

Compile with:
```
gcc -Wall -g testdialog.c -o testdialog `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
```
Then click 'With Buttons'.

screenshot at 2018-01-18 17-58-04



I'll try to rewrite this into msa.

I have played around with GtkGrid, but hopefully I don't have to actually mess with that.

**Comment by raveit65** [comment]
Nice :-)

Here i added a toogle button with 2 horizontal childs , and image and a text.
https://github.com/mate-desktop/atril/blob/16c6e46c38655f223f12b36108fa563fc92bdde3/shell/ev-sidebar-annotations.c#L190
But this is really a lot of work to do this for all deprecated GtkStock buttons.

**Comment by info-cppsp** [comment]
You probably shouldn't use GtkBox anymore.
https://developer.gnome.org/gtk3/stable/gtk-migrating-GtkGrid.html
It is not deprecated yet, but I have read somewhere that it is going to be...

**Comment by raveit65** [comment]
Lol, GtkBoxes are everywhere in code.
.......who paid us to follow their strange ideas?

**Comment by monsta** [comment]
>  It is not deprecated yet, but I have read somewhere that it is going to be...

It's not deprecated in GTK+3, and that's all we need to know now.

**Comment by info-cppsp** [comment]
^Right. :P

Now the Help and Close buttons should also show an icon in the preferences and sensor config dialogs.
They are the replacements for the stock stuff, but I can put in any theme icon.

OFF: thoughts on making UIs with GtkBuilder from .ui files? Like this one:
https://github.com/linuxmint/gtk/blob/master/tests/mydialog.ui

**Comment by raveit65** [comment]
> OFF: thoughts on making UIs with GtkBuilder from .ui files? Like this one:
https://github.com/linuxmint/gtk/blob/master/tests/mydialog.ui

Well, using an UI file make it simpler to add options to a function, so why not....

**Comment by monsta** [comment]
Seems like too much work just to fix small `GtkStock` warnings... I would just leave them alone until migration to GTK+4.

**Comment by raveit65** [comment]
But we can't merge this before 1.20 release as text in buttons isn't translated now.
We need a bit time for translators.
So we can merge it after 1.20 of m-s-a.

**Comment by info-cppsp** [comment]
@monsta 
'Seems like too much work just to fix small GtkStock warnings'
Now you tell me. ;)

As I have read about this GtkStock stuff, it seems like gtk people broke things in the middle of v 3.
That means, that app devs can:
a, use now deprecated code
b, update code, removing deprecated parts
c, move to GTK+ 4

Not nice...

**Comment by raveit65** [comment]
@info-cppsp 
np, we can merge this but not before 1.20 because of missing translations.

**Comment by monsta** [comment]
Unlike some other deprecations, this one continues to work even with 3.22, so it will become really important only with migration to GTK+4.

**Comment by info-cppsp** [comment]
ok then.
I understand if you would want to make the transition in one place, when the time comes.
OTOH we would have to look at less warnings until then.
I would put it in 1.20.1, if the translations are done, but the decision is ofc yours.

**Comment by lukefromdc** [comment]
GTK4 is a bit of a difficult transition for things using custom widgets due to radical changes in the drawing model (GSK) that break drawing many things other than normal GTK widgets.  GSK was why GNOME branched to 4.0 (actually 3.80something at first). Firefox and Libreoffice would have had to start over on all their GTK3 porting if GSK had been merged into a GTK 3.24 without keeping all the old drawing code-and some kind of runtime method to determine whether to use the old or new code, which would have been a real mess.

**Comment by monsta** [comment]
Interesting. Looks like @sc0w managed to replace less lines of code in https://github.com/mate-desktop/mate-panel/pull/712.

**Comment by info-cppsp** [comment]
Thanks to you and @sc0w I have updated the PR.
The Up, Down, Properties buttons still need translations though.

**Comment by raveit65** [comment]
rebased and merged
https://github.com/mate-desktop/mate-sensors-applet/commit/7e4869045b4327cbd8453e7a9b670680f8cfb87d
Thank you

**Pull request closed without merging**
