### PR TITLE
Fix Compilation Warning

### PR DESCRIPTION
**Pull request by zhuyaliang**
Fix Compilation Warning

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This kills most of the non-deprecation warnings, builds and runs fine. We get a few non-deprecation warnings left, though this stop most of them and the remainder could be left for another PR. Here are the ones that are left:
```

i2c-sys-plugin.c:95:17: warning: 'id' may be used uninitialized [-Wmaybe-uninitialized]
   95 |                 g_free(id);
      |                 ^~~~~~~~~~
i2c-sys-plugin.c: In function 'i2c_sys_plugin_test_sensor':
i2c-sys-plugin.c:43:12: note: 'id' was declared here
   43 |     gchar *id;
      |            ^~
In function 'i2c_sys_plugin_add_sensor',
    inlined from 'i2c_sys_plugin_test_sensor' at i2c-sys-plugin.c:132:5:
i2c-sys-plugin.c:96:17: warning: 'label' may be used uninitialized [-Wmaybe-uninitialized]
   96 |                 g_free(label);
      |                 ^~~~~~~~~~~~~
i2c-sys-plugin.c: In function 'i2c_sys_plugin_test_sensor':
i2c-sys-plugin.c:44:12: note: 'label' was declared here
   44 |     gchar *label;
      |            ^~~~~
  CCLD     libi2c-sys.la

```

**Comment by zhuyaliang** [comment]
@lukefromdc The warning has been fixed, please check again

**Comment by lukefromdc** [comment]
After the last change, only deprecation warnings appear. Again builds, install, and runs fine. Looks good to go

**Review by raveit65 — APPROVED** [review]
LGTM,
fixes a lot warnings, thanks.

**Pull request merged**
