### PR TITLE
OOP01 Add GObjects for Sensors and Plugins

### PR DESCRIPTION
**Pull request by info-cppsp**
First part of changing msa to OOP. Adds capability to generate files for GTypes for the enums in msa.
The code is not included or used at the moment.

This is the base of building a Sensor GObject.
In itself it doesn't do anything.

For now I just wanted to share the code.

### CODE REVIEW

**Comment by info-cppsp** [comment]
I have made the MSASensor GObject.
I can include it easily in msa, and it work with the dialog box.
I wanted to include it in the library that is used by the plugins.
After 2 days of trying different includes an Makefile macros, I came to the following conclusion:
I'm gonna have to go retarded on this one.
So I have made 2 new files in the /lib folder.
```c
/* msa-test.h */
#ifndef MSA_TEST_H
#define MSA_TEST_H

void printmsamsg (void);

#endif /* MSA_TEST_H */

/* msa-test.c */
#include "msa-test.h"

#include <syslog.h>

#define MSA_TEST_C

void printmsamsg (void) {
syslog(LOG_ERR, "msa-test.c");
}

```

Using libtool CLI !!! I have:
1. compiled the original sensors-applet-plugin.c and the new msa-test.c into .o and .lo files
2. linked the .lo files to an .la file (made the shared library)
3. installed it on my system

Then rewritten the main msa Makefile to skip the lib subdir, so it won't be recompiled.
Then remade msa, then installed it.
IT WORKS!!

Now I have to figure out how to do the exact same thing with automake...

**Comment by info-cppsp** [comment]
I printed out the link command from the /lib Makefile:
```
echo "@echo "  CCLD    " libmate-sensors-applet-plugin.la;/bin/bash ../libtool --silent --tag=CC   --mode=link gcc  -g -O2 -export-dynamic  -o libmate-sensors-applet-plugin.la -rpath /usr/lib sensors-applet-plugin.lo msa-test.lo -lgio-2.0 -lgobject-2.0 -lglib-2.0"
@echo  CCLD  libmate-sensors-applet-plugin.la;/bin/bash ../libtool --silent --tag=CC   --mode=link gcc  -g -O2 -export-dynamic  -o libmate-sensors-applet-plugin.la -rpath /usr/lib sensors-applet-plugin.lo msa-test.lo -lgio-2.0 -lgobject-2.0 -lglib-2.0
```
What I have used:
```
libtool link gcc -g -O2 -o libmate-sensors-applet-plugin.la sensors-applet-plugin.lo msa-test.lo -rpath /usr/lib/
```
The libtool documentation has that -rpath last.
That turned out to be the culprit and I have found out that it has to go into the LDFALGS in the Makefile.am.
So the /lib/Makefile.am was: (only the end)
```
# also build the libsensorsplugin library
lib_LTLIBRARIES = libmate-sensors-applet-plugin.la

libmate_sensors_applet_plugin_la_SOURCES = sensors-applet-plugin.c 
libmate_sensors_applet_plugin_la_LDFLAGS = -export-dynamic
```
The new version:
```
# also build the libsensorsplugin library
lib_LTLIBRARIES = libmate-sensors-applet-plugin.la

libmate_sensors_applet_plugin_la_SOURCES = sensors-applet-plugin.c msa-test.c msa-test.h
libmate_sensors_applet_plugin_la_LDFLAGS = -export-dynamic -rpath /usr/lib/
```
Now comes cleanup.

**Comment by info-cppsp** [comment]
After a lot of suffering, I have managed to make a test library in the sensor-applet folder, which then gets included into the main plugin lib.
I have updated the PR.
Now I am going to try to build the libraries for the MSASensor.

**Comment by info-cppsp** [comment]
Success! Added new demo 03.
Now I can work on the MSAPlugin.

**Comment by info-cppsp** [comment]
things to remember from the battle:

manual libtool compile, link, install, finish
I have used this to build my test files in the /lib dir into the plugin lib.
```
libtool compile gcc -c msa-test.c

libtool compile gcc -I.. -I../sensors-applet -DHAVE_CONFIG_H -DHAVE_UNISTD_H -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -c sensors-applet-plugin.c

libtool link gcc -o libmate-sensors-applet-plugin.la msa-test.lo sensors-applet-plugin.lo -rpath /usr/lib/
here:
- rpath must be last
- msa-test.lo sensors-applet-plugin.lo or the other way around doesn't matter

copy to /usr/lib
sudo libtool --mode=install install -c libmate-sensors-applet-plugin.la /usr/lib/libmate-sensors-applet-plugin.la

libtool --finish /usr/lib/

then remove SUBDIR lib from main Makefile
make
success
```

In the linking command '-rpath' must be last. This was the main problem. Now, that I have set it explicitly in the /lib/Makefile.am, it is given twice in the generated command, which issues a warning when make-ing, but it works.

-----
Can't use variables in _SOURCES !!! All paths are relative and must be written in full.
`../sensors-applet/msa-test.c`
Manual says that it is a common mistake. (In Makefile.am)

-----
if 2x (.c + .h) files are in the same lib dir and the '#include's are:
.c->.h
.c->.h
if the lib is built with both .c files, this works

-----
if 2x (.c + .h) files are not in the same dir but one set is loaded as a lib from another dir and the '#include's are:
.c->.h
.c->.h
this works with the test files, but not with the msa-sensor files.
In the latter case sensors-applet-plugin.h must include msa-sensor.h.

-----
Can't link a dynamic .la lib, that is installed, into another one. (At least I couldn't.)
I build my new libs in /sensors-applet as noinst_ and then include / link them to the main plugin lib in /lib. See 'Makefile.am's.


-----
plugin research - plugin dlopen
The plugins are loaded with dlopen.
This needs libtool flags in Makefile.ams:
https://www.gnu.org/software/libtool/manual/html_node/Building-modules.html#Building-modules

**Comment by raveit65** [comment]
We create tarballs with distcheck.
./autogen.sh && make && make distcheck
fails at 'make distcheck'
```
 /usr/bin/mkdir -p '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_inst/lib/mate-sensors-applet/plugins'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libacpi.la '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_inst/lib/mate-sensors-applet/plugins'
libtool: warning: relinking 'libacpi.la'
libtool: install: (cd /media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub/plugins/acpi; /bin/sh "/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub/libtool"  --silent --tag CC --mode=relink gcc -g -O2 -module -avoid-version -lgio-2.0 -lgobject-2.0 -lglib-2.0 -o libacpi.la -rpath /media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_inst/lib/mate-sensors-applet/plugins acpi-plugin.lo ../../lib/libmate-sensors-applet-plugin.la -lX11 -lXext )
/usr/bin/ld: cannot find -lmate-sensors-applet-plugin
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libacpi.la' with the above command before installing it
make[4]: *** [Makefile:442: install-pluginLTLIBRARIES] Error 1
make[4]: Leaving directory '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub/plugins/acpi'
make[3]: *** [Makefile:608: install-am] Error 2
make[3]: Leaving directory '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub/plugins/acpi'
make[2]: *** [Makefile:438: install-recursive] Error 1
make[2]: Leaving directory '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub/plugins'
make[1]: *** [Makefile:585: install-recursive] Error 1
make[1]: Leaving directory '/media/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-sensors-applet-dist/mate-sensors-applet-1.19.1/_build/sub'
make: *** [Makefile:801: distcheck] Error 1
```
full log at:
https://www.dropbox.com/s/is66yfeaz9zi654/m-s-a-build-log?dl=0
Note, distcheck checks build/install/uninstall from a generate tarball and create subdirs under srcdir for that.
Run the command for better understanding :-)

**Comment by raveit65** [comment]
@lukefromdc 
Did you test 'make distcheck' ?

**Comment by lukefromdc** [comment]
No, I did not and normally do not

**Comment by lukefromdc** [comment]
Just tested make distcheck, it passed

**Comment by info-cppsp** [comment]
I know about the rpath warning, without it it doesn't work.
ravit65 can't build a distcheck and after I have removed my previous libs, I can't do it either.
There is something wrong with libtools.
It doesn't link the plugin library right.
I'll try to write more about it later today.

**Comment by info-cppsp** [comment]
1st test: master works with distcheck on my system (just to be sure)
2nd test: oop01
./autogen.sh --prefix=/usr
make
sudo make install
compiles and installs this (linking demo 03) without problems, even if I previously remove all msa files from /usr/lib/

**Comment by info-cppsp** [comment]
very sorry guys!
I was stupid enough to set the -rpath in /lib/Makefile.am to a hardcoded `/usr/lib/`
instead that line should be:
`libmate_sensors_applet_plugin_la_LDFLAGS = -export-dynamic -rpath $(libdir) `
let me clean up my files and push this...

**Comment by raveit65** [comment]
@info-cppsp 
`./autogen.sh --prefix=/usr && make && sudo make install`
 works well here with using 
`libmate_sensors_applet_plugin_la_LDFLAGS = -export-dynamic -rpath $(libdir)`

**Comment by raveit65** [comment]
@info-cppsp 
Msa seems to be working fine with your changes. Can you please commit the fix?
Then i can approve the PR.

**Comment by info-cppsp** [comment]
ok. The last time I've tried, it didn't work for me.
It doesn't really matter at this point.

-----
Thanks, but the PR is not finished yet.
My initial goal was to improve the architecture of msa.
But after learning more about it, I am not sure I can do that.
The MSAPlugin GObject is nearly finished, but I couldn't figure out how to use it / link it.
The plugins use a library, that is separate from the main program.
With the the new objects, it would be beneficial to have them both in the plugins and in the main program, I just couldn't figure out how to do that yet.
I may even leave the plugins as they are and make a middle layer in the MSAPlugin to convert the plugins to objects.
That sounds a lot easier.

(Also bc of December I have some other things to do. I wish you all Happy Holidays!
I may get back to this before the year is up...)

**Comment by info-cppsp** [comment]
Bc of the above I have decided to abandon this PR.
GObject is not exactly what I would like it to be.
It would need either boilerplating or using vala to rewrite msa to OOP, both of which are hard to do and to debug.
OR adding features like this/self, inheritance of functions (I'm not exactly sure how that works in GObject and so on...)

**Pull request closed without merging**
